### PR TITLE
Deprecate Presta\SitemapBundle\Event\SitemapPopulateEvent::getGenerator

### LINKED ISSUE #115: [1.5] undefined event->getGenerator
Since the update from 1.4 to 1.5, i have this error :
```
[Symfony\Component\Debug\Exception\UndefinedMethodException]                                                            
  Attempted to call an undefined method named "getGenerator" of class "Presta\SitemapBundle\Event\SitemapPopulateEvent".
```
But I don't see any change in the doc wich use that SitemapPopulateEvent : https://github.com/prestaconcept/PrestaSitemapBundle/blob/master/Resources/doc/5-Usage-Event_Listener.md

### PR DESCRIPTION
**Pull request by yann-eugone**
Fixes #115

### CODE REVIEW

File: Event/SitemapPopulateEvent.php [hunk 1]
```diff
@@ -45,7 +44,17 @@ public function __construct(UrlContainerInterface $urlContainer, $section = null
     }
 
     /**
-     * @return GeneratorInterface
+     * @deprecated in favor of `Presta\SitemapBundle\Event\SitemapPopulateEvent::getUrlContainer()`
+     *
+     * @return UrlContainerInterface
+     */
+    public function getGenerator()
+    {
```
Comment (Koc) [inline Event/SitemapPopulateEvent.php]: You should trigger deprection notice here

**Comment by yann-eugone** [comment]
@Koc seems good ?

**Comment by Koc** [comment]
Yes, only one thing: Symfony usually add `@` before deprecation warning - https://github.com/symfony/symfony/search?p=1&q=E_USER_DEPRECATED&utf8=%E2%9C%93
